### ISSUE TITLE
How to create nested-queries?

### ISSUE THREAD

**Issue by JeetuChoudhary** [sangria-graphql/sangria#160] opened 2016-09-19 12:06 UTC
I want to create following query:

```graphql
{
 store{
   years {
     year
   },
   makes(year:"2015") {
     make
   },
   model(make:"Acura") {
     model
   }
 }
}
```

**Comment by hepin1989** [comment] 2016-09-19 12:11
@JeetuChoudhary as the spec,you need first design your schema,and then you could query against it.

**Comment by OlegIlyenko** [comment] 2016-09-19 12:13
I'm not sure how to approach this question, it looks pretty broad... Do you have some specific issue defining the GraphQL schema?

Just in case, here are a few resources on how you can get started with GraphQL:

* http://sangria-graphql.org/learn/
* http://graphql.org/learn/
* http://try.sangria-graphql.org/

**Comment by JeetuChoudhary** [comment] 2016-09-19 12:50
In query it shows following error: Unit is invalid type for the resulting GraphQL type models.User
This is my schema defination:

val UserObject = ObjectType("User", List[Field[Unit,User]](
    Field("year", ListType(StringType), resolve = _.value.year),
    Field("make", ListType(StringType), resolve= _.value.make),
    Field("model", ListType(StringType), resolve= _.value.model)
    ))
  val MAKE= Argument("make", StringType) 
  val MODEL= Argument("model", StringType)
  val Query = ObjectType("Query", List[Field[UserRepo,Unit]](
    Field("store", UserObject, arguments = MAKE :: MODEL :: Nil, resolve =ctx =>ctx.ctx.store(ctx arg MAKE, ctx arg MODEL))
  ))
  val schema=Schema(query=Query)


case class User( year:List[String], make:List[String], model:List[String])
class UserRepo{
  import scala.collection.mutable.{Map => MMap}
  val years:List[String]=List("1974","1975","1976","1977","1978","1979","1980")
  val make=MMap[String,List[String]](
      "2015" -> List("Acura", "Alfa Romeo", "Aprilia"),
      "2016" -> List("Volvo", "Yamaha")
      )
  val model=MMap[String,List[String]](
      "Acura" -> List("ILX", "MDX", "RDX", "RLX")
      )
     
  def store(mak:String, mod:String)={
    def getYear()=years
      def MakeF(mak:String)=make(mak)
      def ModelF(mod:String)=model(mod)
  } 
}

**Comment by OlegIlyenko** [comment] 2016-09-19 14:57
I see what the problem is. You define your `store` field like this:

```scala
Field("store", UserObject, arguments = MAKE :: MODEL :: Nil, resolve =ctx =>ctx.ctx.store(ctx arg MAKE, ctx arg MODEL))
```

Which imply that the result if the `resolve` function should be of type `User`. Still you have defined the `store` method like this:

```scala
def store(mak:String, mod:String)={
    def getYear()=years
      def MakeF(mak:String)=make(mak)
      def ModelF(mod:String)=model(mod)
  } 
```

which just defines a few functions and (implicitly) return `Unit` instead of `User`. You probably wanted to define something like this, I guess:

```scala
def store(mak:String, mod:String)= {
  User(years, make(mak), model(mod))
} 
```

**Comment by JeetuChoudhary** [comment] 2016-09-19 16:16
Thanks Oleg, It worked.
But this code creates following query:
```
{
 store(make:"2015",model:"Acura")
  {
     year,
    make,
    model
  } 
}
```
But i need to create this query:
```
{
 store{
   years {
     year
   },
   makes(year:"2015") {
     make
   },
   model(make:"Acura") {
     model
   }
 }
}
```

So can you please help me with this. Give some help or reference.

**Comment by OlegIlyenko** [comment] 2016-09-19 19:21
Ok, I see. I'm not quite sure which role `User` case class plays in this code or what the indented logic for these types is, but you can do something like this to define a schema that serves query similar to the one you have described:

```scala
import sangria.schema._
import sangria.execution._
import sangria.macros._
import sangria.marshalling.sprayJson._

class UserRepo {
  import scala.collection.mutable.{Map ⇒ MMap}

  val years: List[String] =
    List("1974", "1975", "1976", "1977", "1978", "1979", "1980")

  val make = MMap[String, List[String]](
    "2015" → List("Acura", "Alfa Romeo", "Aprilia"),
    "2016" → List("Volvo", "Yamaha")
  )

  val model = MMap[String, List[String]](
    "Acura" → List("ILX", "MDX", "RDX", "RLX")
  )
}

val YearArg = Argument("year", StringType)
val MakeArg = Argument("make", StringType)

val StoreType = ObjectType("Store", List[Field[UserRepo, Unit]](
  Field("years", ListType(StringType), resolve = _.ctx.years),
  Field("makes", ListType(StringType),
    arguments = YearArg :: Nil,
    resolve = c ⇒ c.ctx.make.getOrElse(c arg YearArg, Nil)),
  Field("model", ListType(StringType),
    arguments = MakeArg :: Nil,
    resolve = c ⇒ c.ctx.model.getOrElse(c arg MakeArg, Nil))
))

val Query = ObjectType("Query", List[Field[UserRepo, Unit]](
  Field("store", StoreType, resolve = _ ⇒ ())
))

val schema = Schema(Query)

val query =
  graphql"""
    {
      store {
        years
        makes(year: "2015")
        model(make: "Acura")
      }
    }
  """

val result = Executor.execute(schema, query, new UserRepo)
```

The `result` in this case would be a JSON like this:

```json
{
  "data": {
    "store": {
      "years": ["1974", "1975", "1976", "1977", "1978", "1979", "1980"],
      "makes": ["Acura", "Alfa Romeo", "Aprilia"],
      "model": ["ILX", "MDX", "RDX", "RLX"]
    }
  }
}
```

Is it something you tried to archive?

**Comment by JeetuChoudhary** [comment] 2016-09-19 19:35
Yes
Thank You very much Oleg

**Comment by OlegIlyenko** [comment] 2016-09-21 21:28
Since question is answered, I'll close this issue, but please feel free to reopen it if you would like to continue the discussion.

**Closed by OlegIlyenko** 2016-09-21 21:28 UTC
Labels: question

**Comment by JeetuChoudhary** [comment] 2016-09-22 06:13
I want to generate schema.json file and i have created it with the web-pack but now stage is not working on the project. 
Can you please tell me what is happening, why is it not working.

**Comment by OlegIlyenko** [comment] 2016-09-22 08:31
It's hard to tell without additional information since I don't know exactly how your application is organized. Though maybe [sangria-relay-playground](https://github.com/sangria-graphql/sangria-relay-playground) can help you with this - it also generates the schema and uses `webpack`/`babelRelayPlugin`.

**Comment by JeetuChoudhary** [comment] 2016-09-22 11:25
I used same in my project, like same project with my schema and data.

**Comment by anthonysyk** [comment] 2017-11-14 03:10
Is it possible to use the derivation macros to reproduce this ? 

`val YearArg = Argument("year", StringType)
val MakeArg = Argument("make", StringType)

val StoreType = ObjectType("Store", List[Field[UserRepo, Unit]](
  Field("years", ListType(StringType), resolve = _.ctx.years),
  Field("makes", ListType(StringType),
    arguments = YearArg :: Nil,
    resolve = c ⇒ c.ctx.make.getOrElse(c arg YearArg, Nil)),
  Field("model", ListType(StringType),
    arguments = MakeArg :: Nil,
    resolve = c ⇒ c.ctx.model.getOrElse(c arg MakeArg, Nil))
))
`
