### ISSUE TITLE
deriveEnumType fails to enumerate sealed hierarchy members

### ISSUE THREAD

**Issue by shishkin** [sangria-graphql/sangria#159] opened 2016-09-18 14:22 UTC
The fruit example from http://sangria-graphql.org/learn/#enumtype-derivation fails to compile with:

```
[error] /.../Fruit.scala:16: Enum value list is empty
[error]   val FruitType = deriveEnumType[Fruit](
[error]                                        ^
```

Using SBT 0.13.11, Scala 2.11.8 and Sangria 0.7.3.

**Comment by OlegIlyenko** [comment] 2016-09-18 15:41
This is pretty common issue. The problem is the way scala macro discovers these sealed hierarchies of classes/objects. If macro is used before you list all of the members of this enumeration or you use it in different compilation unit (different source file), then macro will not be able to discover all of the members. This is known limitation of scala macros and there is at lest on issue in scala's Jira for this.

So in order to solve this issue you can use the macro **after** all instances of enumeration are defined in the same source file (you can user use a companion object for this as well). Please note, that it has nothing to do with run-time behavior, all this discovery happens at a compile time.

Let me know whether this solves the issue for you.

**Comment by shishkin** [comment] 2016-09-19 13:38
Thanks, it helps. Maybe worth explaining it in the docs?

**Comment by OlegIlyenko** [comment] 2016-09-19 14:29
Yeah, definitely, there is even an issue for this:

https://github.com/sangria-graphql/sangria-website/issues/22

just haven't updated the docs yet

**Comment by OlegIlyenko** [comment] 2016-09-21 21:29
Since question is answered, I'll close this issue, but please feel free to reopen it if you would like to continue the discussion.

**Closed by OlegIlyenko** 2016-09-21 21:29 UTC
Labels: question
