### ISSUE TITLE
How to do a rest call to another api from sangria-graphql project 

### ISSUE THREAD

**Issue by JeetuChoudhary** [sangria-graphql/sangria#163] opened 2016-09-30 10:12 UTC
I want to create a api using sangria which create query and then get from client there desired query and call another api with that query and return response back to client.

I know, i made it so complicated but i am a new to graphql. So help me with this.
Thanks

**Comment by OlegIlyenko** [comment] 2016-09-30 11:28
Generally there is nothing special to an HTTP requests. In a field's `resolve` function you can write an arbitrary logic - you can just return a context value, make a DB query or make an HTTP request to some other service. Here is a small example:

```scala
Field("product", ProductType,
  arguments = Argument("productId", StringType) :: Nil,
  resolve = c ⇒ {
    val product: Future[Product] =
      loadFromExpernalService("http://products.com/products/" + c.arg[String]("productId"))
    
    product
  })
```

If you have a lot of these independent HTTP calls, it can become quite inefficient. In these cases I suggest to use a [deferred values](http://sangria-graphql.org/learn/#deferred-values-and-resolver) feature. 

Recently I also put together a small example app that allows you to define a GraphQL schema directly in browser that delegates all of it's resolution to external HTTP service:

http://toolbox.sangria-graphql.org/proxy

**Comment by JeetuChoudhary** [comment] 2016-10-01 08:49
I didn't get this method:
loadFromExpernalService()

can you please explain
Thanks

**Comment by JeetuChoudhary** [comment] 2016-10-01 09:27
My schema structure like this:

```
{
  PriceQuery(basevehicleidnumber :"19067",parttypeidnumber:"5428",productpartnumber:"W0133-1904743"){
    productpartnumber
    basevehicleidnumber
    parttypeidnumber
    core
    corefee
    corereturnfee
    floorprice
    listprice
    marchentfee
    marchentfeeallocatoin
    markupfactor
    retailprice
    shippingallocation
  }
}

```
In order to fulfill this GraphQL query i call some other API.

**Comment by OlegIlyenko** [comment] 2016-10-01 11:34
sorry, I haven't described `loadFromExpernalService`. It is your own method to load data from particular URL. For instance it can look like this (using play `WSClient` in this example): 

```scala
def loadFromExpernalService(url: String) = 
  client.url(url).execute().map(response ⇒ parsePerson(response))
```

**Comment by JeetuChoudhary** [comment] 2016-10-02 20:26
Thanks, you are very helpful and sorry for late reply 

But i am still having issues regarding:
1. how to pass multiple argument to call rest api and return result and
2.  When i consuming this query 
```
{
  PriceQuery(basevehicleidnumber :"19067",parttypeidnumber:"5428",productpartnumber:"W0133-1904743"){
    productpartnumber
    basevehicleidnumber
    parttypeidnumber
    core
    corefee
    corereturnfee
    floorprice
    listprice
    marchentfee
    marchentfeeallocatoin
    markupfactor
    retailprice
    shippingallocation
  }
}
````

if in case i only want  to return 5 fields(core, corefee,  corereturnfee, floorprice, listprice).
So how can i do this?
Thanks again for all your help

**Comment by OlegIlyenko** [comment] 2016-10-02 20:32
> how to pass multiple argument to call rest api and return result and

you first need to get them from GraphQL query with something like `c.arg[String]("productId")` (as I have shown in the example above) and then you add them to a URL as query parameters, i guess (this depends on your REST API)

> if in case i only want to return 5 fields

hmmm... I'm not sure I understood the question. If you don't need some fields, then you just don't specify then in the GraphQL query

**Comment by JeetuChoudhary** [comment] 2016-10-03 20:41
I got following response:
"resp": "NingWSResponse(200, OK)"
Why is it returning this response and I only want (200, OK).

Any suggestions on how to do this?
Thank you so much for sangria and thank you for your time.

**Comment by OlegIlyenko** [comment] 2016-10-03 20:53
Thanks for the kind words!

Hmmm... It's very hard for me to tell since I don know what you are exactly doing in you application. Maybe you can post a small (reduced) example of the code that represents this particular part of your application. It's very hard to suggest based on the info you have provided in the comment above.

**Comment by JeetuChoudhary** [comment] 2016-10-03 21:02
Thanks for quick reply
```
Schema:
val MailType = ObjectType[Unit, ReturnType](
    "Email", "Email Store", fields[Unit, ReturnType](
      Field("resp", StringType, resolve = _.value.resp)
      ))

Field("Email", MailType,
  arguments = Argument("mailto", StringType) :: Argument("mailfrom", StringType) :: Argument("subject", StringType) :: Argument("content", StringType) ::  Nil,
  resolve = c ⇒ {
    val Return: Future[ReturnType] =
      //c.ctx.loadFromExpernalService("http://52.205.254.169:9002/mail-send/" + c.arg[String]("mailto")+c.arg[String]("mailfrom")+c.arg[String]("subject")+c.arg[String]("content"))
    c.ctx.loadFromExpernalService(c.arg[String]("mailto"),c.arg[String]("mailfrom"),c.arg[String]("subject"),c.arg[String]("content"))
    Return
  })

Data:

case class Email(mailto:String, mailfrom:String, subject:String, content:String)
case class ReturnType(resp:String)

def loadFromExpernalService(mto:String, mfrom:String, sub:String, content:String):Future[ReturnType]={
       ws.url(url).withQueryString(
        "mailto" -> mto,
        "mailfrom" -> mfrom,
        "subject" -> sub,
        "content" -> content
        ).get().map(response ⇒ ReturnType(response.toString()))
  }

```

**Comment by OlegIlyenko** [comment] 2016-10-03 21:10
The issue is that `response` (used in `map` in the line) is a complex object that contains a lot of stuff about the response (like HTTP status, headers, etc). Want you probably want the the response body. You can get is as JSON with `response.json` or as a string with `response.body`

**Comment by JeetuChoudhary** [comment] 2016-10-03 21:23
So if i return response.json then what will be case class and return values in 
```
val MailType = ObjectType[Unit, ReturnType](
    "Email", "Email Store", fields[Unit, ReturnType](
      Field("resp", StringType, resolve = _.value.resp)
      ))
```

**Comment by OlegIlyenko** [comment] 2016-10-03 21:34
well, in this case you probably want to use `response.body` and work with string, unless you model the action JSON structure in GraphQL schema as well.

**Comment by JeetuChoudhary** [comment] 2016-10-03 21:38
but when i use response.body then it returns: "{\"StatusCode\":\"202\"}"

**Comment by OlegIlyenko** [comment] 2016-10-03 21:40
Looks correct to me - this is what other HTTP service returned as a response to your HTTP request

**Comment by JeetuChoudhary** [comment] 2016-10-03 21:42
Yes, i am talking about slashes. 

Again Thank you very much for your time and help

**Comment by JeetuChoudhary** [comment] 2016-10-06 20:02
Hello
```
Schama:

val PriceType = ObjectType[Unit, PriceReturn](
    "Inventory", "Inventory Store", fields[Unit, PriceReturn](
      Field("productpartnumber", StringType, resolve = _.value.productpartnumber),
      Field("basevehicleidnumber", StringType, resolve = _.value.basevehicleidnumber),
      Field("parttypeidnumber", StringType, resolve = _.value.parttypeidnumber),
      Field("core", StringType, resolve = _.value.core),
      Field("corefee", StringType, resolve = _.value.corefee),
      Field("corereturnfee", StringType, resolve = _.value.corereturnfee),
      Field("floorprice", StringType, resolve = _.value.floorprice),
      Field("listprice", StringType, resolve = _.value.listprice),
      Field("marchentfee", StringType, resolve = _.value.marchentfee),
      Field("marchentfeeallocation", StringType, resolve = _.value.marchentfeeallocation),
      Field("markupfactor", StringType, resolve = _.value.markupfactor),
      Field("retailprice", StringType, resolve = _.value.retailprice),
      Field("shippingallocation", StringType, resolve = _.value.shippingallocation)
      ))


Field("Price", PriceType,
  arguments = Argument("productpartnumber", StringType) :: Argument("basevehicleidnumber", StringType) :: Argument("parttypeidnumber", StringType) ::  Nil,
  resolve = c ⇒ {
    val Return: Future[PriceReturn] =
    c.ctx.priceCalculator(c.arg[String]("productpartnumber"),c.arg[String]("basevehicleidnumber"),c.arg[String]("parttypeidnumber"))
    Return
  })


Data:
case class Price(productpartnumber:String, basevehicleidnumber:String, parttypeidnumber:String)
case class PriceReturn(productpartnumber:String, basevehicleidnumber:String, parttypeidnumber:String,
    core:String, corefee:String, corereturnfee:String, floorprice:String, listprice:String, marchentfee:String,
    marchentfeeallocation:String, markupfactor:String, retailprice:String, shippingallocation:String)



def priceCalculator(pn:String, bid:String, pid:String):Future[PriceReturn]={
    ws.url(url).withQueryString(
        "productpartnumber" -> pn,
        "basevehicleidnumber" -> bid,
        "parttypeidnumber" -> pid
        ).get().map(response ⇒ PriceReturn(response.body))
  }
```
Here when I map response to PriceReturn then it shows following error:

" not enough arguments for method apply: (productpartnumber: String, basevehicleidnumber: String, parttypeidnumber: String, core: String, corefee: String, corereturnfee: String, floorprice: String, listprice: String, marchentfee: String, marchentfeeallocation: String, markupfactor: String, retailprice: String, shippingallocation: String)models.PriceReturn in object PriceReturn. Unspecified value parameters basevehicleidnumber, parttypeidnumber, core... "

Any suggestions on what's going on and how to solve this?

**Comment by OlegIlyenko** [comment] 2016-10-06 20:10
The `response.body` is a string. I assume that this string contains a JSON. Is this assumption correct?

It this is true, then you probably need to parse this JSON and then transform it into a case class `PriceReturn`. In your code you have defined a 13 fields in `PriceReturn` class, but then you creating it with just a single String argument.

**Comment by JeetuChoudhary** [comment] 2016-10-06 20:17
Thanks for quick reply
Yes this contains JSON response.
what's a simple way to parse the JSON into the case class? Any suggestion?

**Comment by OlegIlyenko** [comment] 2016-10-06 20:21
since you are using play-json, I would suggest you to check these docs: https://www.playframework.com/documentation/2.5.x/ScalaJson#Json

Also, as was mentioned before, with `response.json` you can get a `JsValue` directly

**Comment by JeetuChoudhary** [comment] 2016-10-06 20:29
can you give any example according to my case

**Comment by JeetuChoudhary** [comment] 2016-10-07 12:40
Hello
```
case class PriceReturn(productpartnumber:String, basevehicleidnumber:String, parttypeidnumber:String,
    core:String, corefee:String, corereturnfee:String, floorprice:String, listprice:String, marchentfee:String,
    marchentfeeallocation:String, markupfactor:String, retailprice:String, shippingallocation:String)

implicit val priceReads: Reads[PriceReturn]=(
    (JsPath \ "productpartnumber").read[String] and
    (JsPath \ "basevehicleidnumber").read[String] and
    (JsPath \ "parttypeidnumber").read[String] and
    (JsPath \ "core").read[String] and
    (JsPath \ "corefee").read[String] and
    (JsPath \ "corereturnfee").read[String] and
    (JsPath \ "floorprice").read[String] and
    (JsPath \ "lastprice").read[String] and
    (JsPath \ "marchentfee").read[String] and
    (JsPath \ "marchentfeeallocation").read[String] and
    (JsPath \ "markupfactor").read[String] and
    (JsPath \ "retailprice").read[String] and
    (JsPath \ "shippingallocation").read[String]
    )(PriceReturn.apply _)
  
  
  def priceCalculator(pn:String, bid:String, pid:String):Future[PriceReturn]={
     ws.url("http://52.205.254.169:9002/price-get").withQueryString(
        "productpartnumber" -> pn,
        "basevehicleidnumber" -> bid,
        "parttypeidnumber" -> pid
        ).get().map(response ⇒ response.json.validate[PriceReturn].get)
       
  }
```
It shows Following Error: java.util.NoSuchElementException: JsError.get

Any suggestion on this?

**Comment by JeetuChoudhary** [comment] 2016-10-10 07:43
Hello
I am facing following error:
JsError(List((/lastprice,List(ValidationError(List(error.path.missing),WrappedArray()))))

Any suggestion how can i resolve this?
Thanks

**Comment by OlegIlyenko** [comment] 2016-10-10 14:21
Looks like a JSON validation error: the `lastprice` field is not present in the JSON response. Of the field is optional, then i would suggest you to define it as such in `PriceReturn`: `lastprice: Option[String]`.

It's also possible that you made a typo and wrote `lastprice` instead of `lastprice`.

**Comment by OlegIlyenko** [comment] 2016-10-10 15:06
I think the original question is clarified now, so I will close it for now. I feel that we are discussing the specifics of JSON parsing with play-json. 

I would suggest to move this discussion in [Gitter chat](https://gitter.im/sangria-graphql/sangria). Also please feel free to open another issue of you are still facing some issues or have question about sangria.

**Closed by OlegIlyenko** 2016-10-10 15:06 UTC
Labels: question
