### ISSUE TITLE
Add context aware custom scalars

### ISSUE THREAD

**Issue by BjRo** [sangria-graphql/sangria#248] opened 2017-05-22 06:27 UTC
Hi @OlegIlyenko,

again congrats to the awesome conference. As we discussed yesterday, here's the write-up of the scalar problem we're facing.

## Context
We're exposing our schema to two types of clients. Native mobile and web clients. Historically native mobile clients in our APIs don't expose the APIs raw, but scramble them based on the current users consumer key. That means if we receive a request from the mobile channel we need to descramble the IDs before passing them on to the resolvers (and scramble the ids when we return a response back to the client). The web part doesn't have to do that.

Our Sangria app is sitting behind our OAuth gateway and gets the consumer key and all oauth related information via HTTP headers passed on from the gateway. The key and some other data in the headers is necessary for successful scrambling / descrambling. 

We tried to implement this with a middleware, but there's one scenario that really doesn't work that well, when you have parametrised queries that also send the `variables`. Ids in there naturally also need to be descrambled.

## Problem
I guess the natural way to solve this would be to use a custom scalar and treat scrambling and descrambling as value coercion. The problem though is that we don't have access to the active context (which holds all the necessary data) in the functions of a custom scalar.

Our problem would become trivial to solve if we figure out a way to allow custom scalar functions to access the context. 

We're happy to help with implementation from our side, if you give us a hint how that could be implemented (/cc @axxiss). 

In order not to break the existing scalar implementation, what do you think about a new `ContextAwareScalarType`?

**Comment by OlegIlyenko** [comment] 2017-05-23 15:24
Thanks a lot for a detailed description. After some experiments, I came up with 2 approaches that have their own set of tradeoffs.

## ContextAwareScalarAlias

This one is the same as `ScalarAlis`, but it also provides access to a context. As I was implementing it, I discovered several places where user context is not available:

* **Default values** - they often rendered in places where context is not available 
* **Query validation** - at the moment validation doesn't know anything about execution specifics and user context in particular

Advantages of this approach:

* More simple from user perspective
* Type-safe 
* Allows value transformation to a different type

I implemented POC and here is an example of how you can use it:

https://github.com/sangria-graphql/sangria/blob/context-aware-scalar-alias/src/test/scala/sangria/execution/ContextAwareScalarSpec.scala

This example works fine and IDs are properly encoded/decoded based on the user context. Unfortunately, there are still quite a few places in the code I marked with TODO and not yet sure how to properly handle. In general, it does not feel right at the moment to introduce it in this form. The main reason is that it makes a lot of other features (like schema rendering, validation, etc.) dependent on a user context. So I think I would prefer the second approach.

## Middleware-based scalar value transformation

In this approach, I added 2 new middleware traits:

* `MiddlewareToScalar`
* `MiddlewareFromScalar`

They allow to do the same thing, but the value type is fixed, so if your ID is a `String`, you can't change it to some other type, like `UserId` (though with some creativity and scalar aliases one can make it possible, I think :) ). An example can be found here:

https://github.com/sangria-graphql/sangria/blob/context-aware-scalar-alias/src/test/scala/sangria/execution/ScalarMiddlewareSpec.scala

Advantages of this approach:

* Middleware can be chained together 
* Middleware can be disabled/enabled at execution time
* Has much less impact on other features

## Snapshot version

I already published a snapshot. I would appreciate if you could try these 2 approaches and give your feedback on both of them:

```scala
resolvers += "Sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
libraryDependencies += "org.sangria-graphql" %% "sangria" % "1.2.2-SNAPSHOT"
```

**Comment by Axxiss** [comment] 2017-05-24 14:04
First of all, many thanks for the great support! 😃 

## Context aware scalar

 - Too many places where context is not available or hard to get
 - We would need to add a flag to the context to indicate whether or not encoding is enabled
 - I'm not a big fan of God objects, so I prefer not to add functionality to the context itself (encode/decode)
- Not sure if it would be possible to implementing it without modifying current schema
 
Didn't implemented it, If you think it worth a shot, on next Monday (as I'll be off for a few days) I can give it a go)


## Middleware
 - easy activation, if request is cookie based we don't add the middleware to the engine, if its mobile yes
 - reduce side effects
 - can be integrated without changing the schema
 - consistency: have all 3 possible levels on a middleware
    - from/to outside world
    - before/after query
    - before/after field 

I just refactored our solution to use the middleware without using `Alias` and it worked out smoothly. **I would go with the middleware approach.**

**Comment by OlegIlyenko** [comment] 2017-05-24 14:20
@Axxiss thanks a lot for the feedback! 

I think the middleware-based approach is the way to go. I at the moment it does not provide access to field info or middleware state (`QueryVal` and `FieldVal`), let's see whether it would be possible to add support for these as well. 

I will discard `context-aware-scalar-alias` branch and will create the new one with only new middleware traits.

**Comment by BjRo** [comment] 2017-06-01 15:48
So I've written more specs to test out the middleware approach today. Just to give you some idea, what we're doing, here's a snip of the unscrambling of ids:

```scala
case class FieldScramblingViolation(id: String) extends ValueCoercionViolation(s"Failed to unscramble ${id}")

class FieldScrambling extends MiddlewareFromScalar[MobileRequestContext]  {
  override def fromScalar(value: Any, inputType: InputType[_], ctx: MobileRequestContext): Option[Either[Violation, Any]] = {
    inputType match {
      case IDType => {
        Scrambler.unscramble(value.toString, extractSalt(ctx)) match {
          case Some(id) => Some(Right(id))
          case None => Some(Left(FieldScramblingViolation(value.toString)))
        }
      }
      case _ => None
    }
  }
}
```
Judging from our tests, the happy path already works out pretty well. However the path where the `Either` returns `Left` doesn't seem to work at the moment. Execution continuous and the invalid argument reaches the resolver. 

Any idea?

**Comment by BjRo** [comment] 2017-06-01 16:07
My gut feeling is that this is caused because we wrap around the standard `IDType` scalar and don't use a custom one. But I haven't looked into the code yet.

**Comment by OlegIlyenko** [comment] 2017-06-01 16:33
@BjRo thanks for testing it further! It's an interesting issue. In my tests I also has error cases, but they worked pretty well:

https://github.com/sangria-graphql/sangria/blob/0cad467594ef4f19dc030ba57b349ea0500acccb/src/test/scala/sangria/execution/ScalarMiddlewareSpec.scala#L90

It would be great if you could create a small self-contained test like this one that reproduces the issue. 

I also just checked this test with `IDType` instead of a type alias (`EncodedIdType`), but it still produces same results (thanks for a hint, btw!).

**Comment by BjRo** [comment] 2017-06-02 07:40
I think I've got it narrowed down. The behaviour we see in our code base has to do with __default values in the argument definition__. 

I don't think we use that in the real code, but it's part of the test schema I'm using. If I remove the default value from the argument definition I get the same behaviour as in your specs 👍 

Adding the default value results apparently in falling back to the default value, if the passed in value could not be coerced (and the coercion error is swallowed). 

I don't know if that is accidental or intended behaviour. Do you still need a test case for this, or is this description sufficient?

**Comment by BjRo** [comment] 2017-06-02 08:07
@OlegIlyenko Another thing I've noticed: Coercion errors from the new middleware do not trigger sangrias exception handler.

Also errors from the middleware (e.g. returning `Some(Left(violation))` don't change the output of the executor into a `Failure` (with a `VariableCoercionError`).

I'm pretty certain the first one is a bug. Unsure about the second one.

**Comment by BjRo** [comment] 2017-06-02 15:21
So I've made a test that shows different behaviour when default are added to the mix. https://github.com/BjRo/sangria/commit/29e567d1076362588f915eeca3ad7dc2b8bb44cb

This test fails. It doesn't report the `Field 'id' has wrong value: invalid id. (line 5, column 26)` on `t3` anymore.

**Comment by OlegIlyenko** [comment] 2017-06-06 13:22
@BjRo thanks a lot for digging deeper into it and creating the test! I created a PR for it merged it myself :)

The issue is fixed now (and a few other issues I found along the way). I published new snapshot, it would be great if you could check it again.

**Comment by Axxiss** [comment] 2017-06-06 15:29
@OlegIlyenko Which should be the behaviour regarding error handling?

Not sure if I'm missing something or not. For the current implementation, coercion errors details are returned but it seems that sangria's exception handler is not being called. 🤷‍♂️ 

```
[error]     {
[error]      "data" : null,
[error]      "errors" : [ {
[error]        "message" : "Argument 'id' has wrong value: Failed to unscramble '12344_WRONG'. (line 3, column 27):\n          profileJSON(id: \"12344_WRONG\") {\n                          ^",
[error]        "path" : [ "profileJSON" ],
[error]        "locations" : [ {
[error]          "line" : 3,
[error]          "column" : 27
[error]        } ]
[error]      }
```

**Comment by OlegIlyenko** [comment] 2017-06-06 15:44
@Axxiss The coercion violations are not part of the user-defined exception-handling mechanism, at least not at the moment.

The exception handler is defined like this:

```scala
type ExceptionHandler = PartialFunction[(ResultMarshaller, Throwable), HandledException]
```

Neither `Violation` nor `FieldCoercionViolation` (which is produced in mentioned scenario) extend the `Throwable` or `Exception`. 

Do you have a use-case for custom error handler that also can handle and potentially transform violations? If so, then I would suggest to open a separtate issue and discuss it there. Would be very interested to hear about a use-case.

**Comment by BjRo** [comment] 2017-06-06 16:07
>The coercion violations are not part of the user-defined exception-handling mechanism

@OlegIlyenko I think for variables they are via `VariableCoercionError`. That's what got us confused. We expected symmetry for arguments in that regard. 

Just to give you an idea what our use case is: We basically extend sangrias errors before sending them to the client. This includes for instance adding an error id to the error (such as `RESOLVE_FAILED`, or `QUERY_ANALYISIS_FAILED`). All of our errors are handed out in the same format. This is roughly how we do it:
 
```scala
object Exceptions {
  import StatusCodes._

  val sangriaRuntimeExceptionHandler: Executor.ExceptionHandler = {
    case (m, ex: MissingParentFieldError) => {
      val details = Seq("fieldName" -> m.scalarNode(ex.fieldName, "String", Set.empty))

      HandledException("Missing field in parent selection",
                       Map(
                         "id"      -> m.scalarNode("MISSING_PARENT_FIELD", "String", Set.empty),
                         "details" -> m.mapNode(details)
                       ))
    }

    case (m, ex: RequestError) => {
      HandledException(
        "Could not resolve field",
        Map[String, ResultMarshaller#Node](
          "id"      -> m.scalarNode("RESOLVE_ERROR", "String", Set.empty),
          "details" -> (ex.json.getOrElse(JObject()): Json4sJacksonResultMarshaller.Node)
        )
      )
    }

    case (m, _: MissingIdError) => {
      HandledException(
        "This node needs to request the 'id' field because it's batched",
        Map(
          "id"      -> m.scalarNode("RESOLVE_ERROR", "String", Set.empty),
          "details" -> m.mapNode(Seq())
        )
      )
    }

    case (m, _) => {
      HandledException("Could not resolve field",
                       Map(
                         "id"      -> m.scalarNode("RESOLVE_ERROR", "String", Set.empty),
                         "details" -> m.mapNode(Seq())
                       ))
    }
  }

  def mask(throwable: Throwable): (StatusCode, JObject) = throwable match {
    case ex: SyntaxError =>
      val position = ex.originalError.position
      toError("SYNTAX_ERROR", "The supplied query contains syntax errors", ("line" -> position.line) ~ ("column" -> position.column))

    case ValidationError(violations, _) =>
      val details: JObject = "violations" -> violations.map(_.errorMessage)
      toError("QUERY_ANALYSIS_ERROR", "The supplied query contains semantic errors", details)

    case VariableCoercionError(violations, _) =>
      val details: JObject = "violations" -> violations.map(_.errorMessage)
      toError("ERRONEOUS_VARIABLES", "The supplied variables don't fulfill the schema requirements", details)

    case UnauthorizedAccessException =>
      toError("ACCESS_NOT_ALLOWED", "User credentials missing or invalid", statusCode = Unauthorized)

    case _ =>
      toError("INTERNAL_SERVER_ERROR", "Ooops, something unexpected happened while executing the request ...", JObject(), InternalServerError)
  }

  private def toError(name: String, description: String, details: JObject = JObject(), statusCode: StatusCode = BadRequest): (StatusCode, JObject) = {
    val jsonError = ("id" -> name) ~
      ("message"   -> description) ~
      ("locations" -> JArray(List())) ~
      ("path"      -> JArray(List())) ~
      ("details"   -> details)

    val json = ("data" -> JNull) ~ ("errors" -> List(jsonError))

    statusCode -> json
  }
}
```

The new coercion error in would be the only one that we can't really handle that way. It's not a big super urgent issue though and we can deal with it separately. 

Should I create a separate issue?

**Comment by OlegIlyenko** [comment] 2017-06-06 16:28
Yeah, it would be great if you can create a new issue so that we can more
easily track the progress and have a better context. You previous comment
is quite good 👍🏻, I would just copy/paste it in the description. And I
will look at it in more detail a bit later.

**Comment by BjRo** [comment] 2017-06-06 19:01
👍 Done

**Comment by BjRo** [comment] 2017-06-08 15:42
Totally forget to get back to you regarding this one. In general we're very happy with the snapshot version. 

Besides #252 (where we already decided to discuss this in a separate issue) there's only one other, minor observation I have:

`fromScalar` and `toScalar` are not symmetric in their return types. At least in our case there might be a scenario where it make sense to return an `Either` instead of an `Option` from  `toScalar`.  If the related HTTP header is missing in our scenario we can't encode the scalar (and should probably fail). Right now we can't properly express this via the type system, but the scenario is also edge casy (system configuration error, so no blocker for us). But I thought I mentioned it anyway :-)

In general a big, big thank you for your help so far with this ❤️

**Comment by OlegIlyenko** [comment] 2017-06-13 21:48
Thanks for the feedback! It is quite interesting. I think I always had this assumption that scalar values can't fail when serialized to the user (and if they fail for some reason that it is quite an exceptional situation, like OOM), but need validation when deserialized from the user input. This is where this asymmetry comes from

This dynamic is, of course, different when middleware is involved. Thanks for pointing this out! I can change  `toScalar` signature like this, and make it symmetric:

```scala
def toScalar(value: Any, inputType: InputType[_], ctx: Ctx): Option[Either[Violation, Any]]
```

Though I have a question about the use-case. If header is not present, but user asked for an encoded ID, wouldn't it be better to validate it on a query validation phase or in query reducer, even before the query is executed? If it is a clear client configuration error than it can be immediately rejected with 400 HTTP status. Or did I miss something?

**Comment by BjRo** [comment] 2017-06-14 16:23
>Though I have a question about the use-case. If header is not present, but user asked for an encoded ID, wouldn't it be better to validate it on a query validation phase or in query reducer, even before the query is executed? If it is a clear client configuration error than it can be immediately rejected with 400 HTTP status. Or did I miss something?

No, you're absolutely right. We talked about it internally and that's how we've implemented it now. Simpler :-). 

From our point making `toScalar` and `fromScalar` symmetric is not strictly necessary.  Both solutions would work for us.

**Closed** 2017-06-16 21:33 UTC
Labels: feature
